
---
include:
  - board: nice_nano_v2
    shield: sofle_dongle dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_international
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DUSE_INTERNATIONAL_LAYOUT
  - board: nice_nano_v2
    shield: sofle_dongle dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_receptor_abnt2
  - board: nice_nano_v2
    shield: sofle_left
    artifact-name: sofle_esquerdo
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: sofle_right
    artifact-name: sofle_direito
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset-firmware
